export interface SimulationStepInfo {
  step: number;
  title: string;
  badge: string;
  hardwareStage: string;
  description: string;
  signalFlow: string;
  mathFormula?: string;
  activeNode: string;
}

export const SIMULATION_STEPS: SimulationStepInfo[] = [
  {
    step: 1,
    title: "Environmental Acoustic Stress",
    badge: "STAGE 01 // SOUND FIELD",
    hardwareStage: "External Environment",
    description: "demanding high-intensity acoustic field generated by helicopter rotor blade pass frequencies (BPF 17-25 Hz harmonics), jet turbine whine, and vehicle diesel propulsion.",
    signalFlow: "Surrounding Noise d(t) → Acoustic Air Propagation",
    mathFormula: "d(t) = \\sum_{k=1}^K A_k \\cos(2\\pi k f_0 t + \\phi_k) + w(t)",
    activeNode: "ENVIRONMENT"
  },
  {
    step: 2,
    title: "Reference Microphone Capture",
    badge: "STAGE 02 // TRANSDUCTION",
    hardwareStage: "External Reference Mic (LEFT Ear Cup)",
    description: "The ruggedized omnidirectional reference microphone mounted on the exterior of the LEFT ear cup captures the incoming primary acoustic noise field before it enters the ear canal.",
    signalFlow: "Acoustic Pressure P_ref(t) → Transducer Voltage x(t)",
    mathFormula: "x(n) = \\mathcal{Q}\\{S_{ref} \\cdot P_{ref}(nT_s)\\}",
    activeNode: "REF_MIC"
  },
  {
    step: 3,
    title: "Audio HAT Ingest & DMA Buffer",
    badge: "STAGE 03 // DIGITIZATION",
    hardwareStage: "Custom Audio Interface HAT → Raspberry Pi",
    description: "The low-latency audio codec samples at 48 kHz / 24-bit via I2S bus. Direct Memory Access (DMA) transfers small 64-sample frames into the Raspberry Pi RAM with sub-2ms buffer latency.",
    signalFlow: "x(n) → I2S DMA Ring Buffer → Kernel Audio Subsystem",
    mathFormula: "Frame\\,\\mathbf{x}_m = [x[mB], x[mB+1], \\dots, x[mB+B-1]]^T",
    activeNode: "AUDIO_INGEST"
  },
  {
    step: 4,
    title: "Audio Intelligence: YAMNet Classification",
    badge: "STAGE 04 // AI EMBEDDING",
    hardwareStage: "YAMNet MobileNet Engine (Raspberry Pi)",
    description: "Framed audio passes through log-mel spectrogram extraction. YAMNet generates 1024-dimensional temporal embeddings fed to a task-specific classifier to categorize noise as Stationary, Non-Stationary, or Impulsive.",
    signalFlow: "Audio Frame → STFT Mel Filterbank → MobileNet → Taxonomy",
    mathFormula: "\\mathbf{e}_m = \\text{YAMNet}(\\mathbf{M}_{log}), \\quad \\mathbf{p} = \\text{Softmax}(\\mathbf{W}_c \\mathbf{e}_m)",
    activeNode: "YAMNET"
  },
  {
    step: 5,
    title: "Intelligent State Controller",
    badge: "STAGE 05 // DECISION MATRIX",
    hardwareStage: "Heuristic DSP Controller",
    description: "Synthesizes YAMNet taxonomy, Voice Activity Detection (VAD) confidence, and fast DSP impulse metrics to dynamically adjust adaptive filter step-size \\mu and enable voice-pass filters.",
    signalFlow: "Class + VAD + Impulse Telemetry → Filter Parameter Matrix",
    mathFormula: "\\mu(n) = \\alpha_{class} \\cdot \\mu_{base} \\cdot [1 - \\gamma \\cdot VAD(n)]",
    activeNode: "CONTROLLER"
  },
  {
    step: 6,
    title: "FxLMS Anti-Noise Synthesis",
    badge: "STAGE 06 // ADAPTIVE FILTERING",
    hardwareStage: "DSP Execution Core (Raspberry Pi)",
    description: "Normalized Filtered-X Least Mean Squares (FxLMS) applies secondary path estimate \\hat{S}(z) to the reference signal and convolves with adaptive weights W(z) to generate destructive anti-noise.",
    signalFlow: "Reference x(n) → Filter W(z) → Anti-Noise Signal y(n)",
    mathFormula: "y(n) = \\mathbf{w}^T(n) \\mathbf{x}(n), \\quad x'(n) = \\hat{s}(n) * x(n)",
    activeNode: "FXLMS"
  },
  {
    step: 7,
    title: "Acoustic Cancellation at Ear Canal",
    badge: "STAGE 07 // DESTRUCTIVE INTERFERENCE",
    hardwareStage: "Internal Speaker Driver → Acoustic Cavity",
    description: "The anti-noise signal is amplified and driven through the internal neodymium speaker. In the acoustic cavity between cushion and ear drum, the anti-phase sound wave destructively cancels the ambient noise.",
    signalFlow: "Speaker Output -y'(t) + Ambient Leakage d'(t) → Residual Acoustic Sum",
    mathFormula: "P_{res}(t) = P_{ambient}(t) - P_{anti}(t) \\approx 0",
    activeNode: "ACOUSTIC_SUM"
  },
  {
    step: 8,
    title: "Residual Error Transduction",
    badge: "STAGE 08 // ERROR SENSING",
    hardwareStage: "Internal Error Microphone",
    description: "An ultra-compact error microphone placed right next to the speaker aperture continuously measures the residual acoustic pressure e(n) inside the ear cavity to detect cancellation imperfections.",
    signalFlow: "Ear Cavity Residual Pressure → Error Mic Transducer → ADC",
    mathFormula: "e(n) = d(n) - y'(n) + v(n)",
    activeNode: "ERROR_MIC"
  },
  {
    step: 9,
    title: "Closed-Loop Adaptive Weight Update",
    badge: "STAGE 09 // FEEDBACK CONVERGENCE",
    hardwareStage: "Feedback Adaptation Pipeline",
    description: "The measured error e(n) is correlated with the filtered reference vector x'(n). The gradient algorithm updates filter weights W(z) to track changing rotor speeds and vehicle acoustic profiles.",
    signalFlow: "Error e(n) × Filtered Ref x'(n) → Weight Vector Update",
    mathFormula: "\\mathbf{w}(n+1) = \\mathbf{w}(n) + \\frac{\\mu}{\\|\\mathbf{x}'(n)\\|^2 + \\epsilon} e(n) \\mathbf{x}'(n)",
    activeNode: "ADAPTIVE_UPDATE"
  },
  {
    step: 10,
    title: "Soldier Receives Clear Tactical Voice",
    badge: "STAGE 10 // SPEECH PRESERVATION",
    hardwareStage: "Operator Auditory Canal",
    description: "Environmental acoustic roar is substantially attenuated while high-intelligibility tactical radio voice formants and team communication from the boom microphone pass through unhindered.",
    signalFlow: "Preserved Speech s(t) + Minimized Residual e(t) → Operator Ear",
    mathFormula: "r(t) = s(t) + e_{attenuated}(t), \\quad \\text{Speech Intelligibility Preserved}",
    activeNode: "OPERATOR_EAR"
  }
];

// Mathematical function to compute illustrative simulated waveforms for canvas visualization
export function generateWaveformSamples(
  count: number,
  timeOffset: number,
  noiseSources: Record<string, boolean>,
  speechActive: boolean,
  ancActive: boolean,
  impulseActive: boolean
): { before: number[]; after: number[]; spectrumBefore: number[]; spectrumAfter: number[] } {
  const before: number[] = new Array(count);
  const after: number[] = new Array(count);

  for (let i = 0; i < count; i++) {
    const t = timeOffset + (i / count) * 0.05; // 50ms window
    
    // 1. Environmental noise synthesis
    let noise = 0;
    if (noiseSources.helicopter) {
      // 22 Hz BPF fundamental + harmonics
      noise += 0.55 * Math.sin(2 * Math.PI * 22 * t);
      noise += 0.35 * Math.sin(2 * Math.PI * 44 * t + 0.4);
      noise += 0.25 * Math.sin(2 * Math.PI * 66 * t + 0.8);
      noise += 0.20 * Math.sin(2 * Math.PI * 132 * t + 1.2);
    }
    if (noiseSources.vehicle) {
      // Engine rumble + low broadband
      noise += 0.45 * Math.sin(2 * Math.PI * 35 * t);
      noise += 0.30 * Math.sin(2 * Math.PI * 70 * t + 0.5);
      noise += (Math.random() - 0.5) * 0.2;
    }
    if (noiseSources.wind) {
      // Low frequency turbulence
      noise += 0.35 * Math.sin(2 * Math.PI * 12 * t) * (1 + 0.5 * Math.sin(2 * Math.PI * 3 * t));
      noise += (Math.random() - 0.5) * 0.3;
    }
    if (noiseSources.machinery) {
      noise += 0.4 * Math.sin(2 * Math.PI * 120 * t) + 0.25 * Math.sin(2 * Math.PI * 240 * t);
    }
    if (noiseSources.crowd) {
      noise += (Math.random() - 0.5) * 0.4;
    }
    if (impulseActive || noiseSources.impulse) {
      // Sudden sharp Dirac-like peak
      const impulsePhase = (t * 2) % 1.0;
      if (impulsePhase < 0.04) {
        noise += 1.8 * Math.sin(2 * Math.PI * 400 * t);
      }
    }

    // 2. Speech synthesis (formant harmonics at 300 - 2500 Hz)
    let speech = 0;
    if (speechActive) {
      const speechEnvelope = 0.5 + 0.5 * Math.sin(2 * Math.PI * 3 * t);
      speech += speechEnvelope * (
        0.45 * Math.sin(2 * Math.PI * 320 * t) +
        0.35 * Math.sin(2 * Math.PI * 850 * t + 0.2) +
        0.25 * Math.sin(2 * Math.PI * 1800 * t + 0.6)
      );
    }

    // Input signal = Noise + Speech
    const rawInput = noise + speech;
    before[i] = Math.max(-1.5, Math.min(1.5, rawInput));

    // After ANC signal
    // Destructive interference attenuates noise by ~85-92% when ANC is active, leaving speech intact
    if (ancActive) {
      const residualNoise = noise * 0.12; // Attenuated noise
      after[i] = Math.max(-1.5, Math.min(1.5, residualNoise + speech));
    } else {
      after[i] = before[i];
    }
  }

  // Generate 32-bin simulated FFT spectrum for both
  const spectrumBins = 32;
  const spectrumBefore = new Array(spectrumBins);
  const spectrumAfter = new Array(spectrumBins);

  for (let b = 0; b < spectrumBins; b++) {
    // Frequency bins from 0 to 4000 Hz
    let energyBefore = 0.05 + Math.random() * 0.05;
    
    // Low frequency rotor peaks (bins 0 to 6)
    if (noiseSources.helicopter && b < 6) {
      energyBefore += 0.85 - b * 0.1;
    }
    if (noiseSources.vehicle && b < 8) {
      energyBefore += 0.7 - b * 0.06;
    }
    if (noiseSources.wind && b < 4) {
      energyBefore += 0.6;
    }
    // Speech formant region (bins 4 to 18)
    if (speechActive && b >= 4 && b <= 18) {
      energyBefore += 0.45 * Math.sin(((b - 4) / 14) * Math.PI);
    }
    if (impulseActive && b < 24) {
      energyBefore += 0.5;
    }

    spectrumBefore[b] = Math.min(1.0, energyBefore);

    // After ANC: Low frequencies (bins 0 to 10) are substantially suppressed, speech bins (4 to 18) preserved
    if (ancActive) {
      let energyAfter = energyBefore;
      if (b < 10) {
        energyAfter *= 0.15; // Low frequency ANC reduction
      }
      if (speechActive && b >= 4 && b <= 18) {
        // Speech preserved
        energyAfter = Math.max(energyAfter, 0.45 * Math.sin(((b - 4) / 14) * Math.PI));
      }
      spectrumAfter[b] = Math.min(1.0, energyAfter);
    } else {
      spectrumAfter[b] = spectrumBefore[b];
    }
  }

  return { before, after, spectrumBefore, spectrumAfter };
}
